#!/bin/bash
# Core Realty CRM — double-click this file to run it on localhost.
# macOS opens .command files in Terminal automatically.
# Stop the server with Ctrl+C, then close the Terminal window.

cd "$(dirname "$0")" || exit 1

echo ""
echo "  Core Realty CRM — Phase 1"
echo "  ─────────────────────────────────────────"
echo ""

# --- 1. Is Node installed? -------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
  # Homebrew and nvm installs often aren't on PATH for double-clicked scripts.
  for p in /opt/homebrew/bin /usr/local/bin "$HOME/.nvm/versions/node"/*/bin; do
    [ -x "$p/node" ] && export PATH="$p:$PATH" && break
  done
fi

if ! command -v node >/dev/null 2>&1; then
  echo "  Node.js isn't installed (or isn't on PATH)."
  echo ""
  echo "  Install it, then double-click this file again:"
  echo "    https://nodejs.org  — download the LTS build"
  echo ""
  echo "  Or, if you use Homebrew:  brew install node"
  echo ""
  read -n 1 -s -r -p "  Press any key to close."
  exit 1
fi

NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
if [ "$NODE_MAJOR" -lt 20 ]; then
  echo "  Node $(node -v) found, but this needs Node 20 or newer."
  echo "  Update from https://nodejs.org and try again."
  echo ""
  read -n 1 -s -r -p "  Press any key to close."
  exit 1
fi
echo "  Node $(node -v)"

# --- 2. Config -------------------------------------------------------------
if [ ! -f .env ]; then
  echo "  Creating .env for local use…"
  # Written from scratch, NOT copied from .env.example and appended to.
  # dotenv resolves a repeated key to the last occurrence, but `grep -m1` reads
  # the first — append and those two disagree, and you spend an afternoon
  # wondering why the token on screen isn't the token the server wants.
  RAND() { node -e "console.log(require('crypto').randomBytes(24).toString('hex'))"; }
  cat > .env <<EOF
# --- generated by start.command for LOCAL USE ONLY ---
# Regenerate every secret below before this goes anywhere near production.
# See the checklist in README.md.
PORT=3400
NODE_ENV=development
DATABASE_URL=
PGLITE_DIR=./.pgdata
WEBSITE_INGEST_SECRET=$(RAND)
GOOGLE_WEBHOOK_KEY=$(RAND)
META_VERIFY_TOKEN=$(RAND)
META_APP_SECRET=
META_PAGE_ACCESS_TOKEN=
META_GRAPH_VERSION=v21.0
ADMIN_TOKEN=local-preview
EOF
fi

# tail -1 mirrors dotenv's last-wins behaviour if the file was hand-edited.
ADMIN=$(grep '^ADMIN_TOKEN=' .env | tail -1 | cut -d= -f2-)
[ -z "$ADMIN" ] && ADMIN="local-preview"
PORT=$(grep '^PORT=' .env | tail -1 | cut -d= -f2- | tr -d ' ')
[ -z "$PORT" ] && PORT=3400

# Bail early with a readable message rather than letting node crash on bind.
if lsof -nP -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; then
  echo ""
  echo "  Port $PORT is already in use:"
  lsof -nP -iTCP:"$PORT" -sTCP:LISTEN | tail -n +2 | awk '{print "    " $1 "  pid " $2}'
  echo ""
  echo "  Edit PORT= in .env and run this again."
  echo ""
  read -n 1 -s -r -p "  Press any key to close."
  exit 1
fi

# --- 3. Dependencies -------------------------------------------------------
if [ ! -d node_modules ] || [ ! -d node_modules/express ]; then
  echo "  Installing dependencies (one time, ~30s)…"
  npm install --silent || { echo "  npm install failed."; read -n 1 -s -r -p "  Press any key to close."; exit 1; }
fi
echo "  Dependencies ready"

# --- 4. Sample data --------------------------------------------------------
if [ ! -d .pgdata ]; then
  echo "  Seeding sample leads…"
  npm run seed --silent >/dev/null 2>&1 || echo "  (seed skipped)"
fi

# --- 5. Go -----------------------------------------------------------------
echo ""
echo "  ─────────────────────────────────────────"
echo "    http://localhost:$PORT"
echo "    Admin token:  $ADMIN"
echo "  ─────────────────────────────────────────"
echo ""
echo "  The browser will open in a moment. Paste the token when it asks."
echo "  Press Ctrl+C here to stop the server."
echo ""

( sleep 3; open "http://localhost:$PORT" ) &
npm start
